package org.firstinspires.ftc.teamcode.opmodes.autonomous;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.robots.CompetitionRobot;
import org.firstinspires.ftc.teamcode.robots.CompetitionRobotI;
import org.firstinspires.ftc.teamcode.robots.drivetrains.mecanum.MecanumDriveInput;

@Autonomous(name="BlueOutside")
public class BlueOutside extends LinearOpMode {
    @Override
    public void runOpMode() {
        CompetitionRobotI robot = CompetitionRobot.instantiate(hardwareMap);
        waitForStart();
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(791);
        robot.driveBySticks(new MecanumDriveInput(7.732697716841073E-4, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(33);
        robot.driveBySticks(new MecanumDriveInput(0.371981726574546, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.760614587995176, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(835);
        robot.driveBySticks(new MecanumDriveInput(0.8, 2.942330697857297E-6, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.8, 0.0018503921535399936, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.8, 0.1583708331154009, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.3600919190510958, 0.46261542243022674, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(53);
        robot.driveBySticks(new MecanumDriveInput(0.12096469607021738, 0.722543541016994, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(29);
        robot.driveBySticks(new MecanumDriveInput(0.010038101258904406, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(29);
        robot.driveBySticks(new MecanumDriveInput(0.004847638130838766, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.004212055625910014, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(521);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.0018503921535399936));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(51);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.09962501407580679));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.4092156171283124));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.4909745467016734));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.5204695901645724));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(79);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.5356500521270292));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(564);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.3484582091687397));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.006304360327048331));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(79);
        robot.driveBySticks(new MecanumDriveInput(0.0, 2.942330697857297E-6, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.019669090855358604, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.07256597038570443, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.1871661925660837, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(86);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.002223185106844592));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.219256168453269));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(26);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(125);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.5993233445002052));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(23);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.044791322943135335));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(75);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.28387778867124064, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(58);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.2940334634944208, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(114);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.02141131730120552, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(52);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.0018503921535399936));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(25);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.5356500521270292));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(88);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.01647335237122514));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(55);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.018024033741088605, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(22);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.11536970916775731, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.07256597038570443, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0015217918779346867, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(206);
        robot.driveBySticks(new MecanumDriveInput(0.0, 2.6519064606397182E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.371981726574546, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(162);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4092156171283124, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0018503921535399936, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(252);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.06110105771077212, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5668909112833928, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(68);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.16527056709357968, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(58);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(443);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.012359729889232902, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(20);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.3600919190510958, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(51);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(76);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.07668417689676373, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(564);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(771);
        robot.driveBySticks(new MecanumDriveInput(0.0, -2.6519064606397182E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(14);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.219256168453269, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(58);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.7039938025144066, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1120);
        robot.driveBySticks(new MecanumDriveInput(5.301529950883216E-5, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(9.303438608190281E-5, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(2.247940499531374E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(5.935607817367757E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(7.732697716841073E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0018503921535399936, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.005544144454534878, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(60);
        robot.driveBySticks(new MecanumDriveInput(0.01647335237122514, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(16);
        robot.driveBySticks(new MecanumDriveInput(0.023253501292314464, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.029407688581613814, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(51);
        robot.driveBySticks(new MecanumDriveInput(0.034061380626966085, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(65);
        robot.driveBySticks(new MecanumDriveInput(0.0026429595005789787, -0.1723678461856297, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, -4.4410399168743177E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(33);
        robot.driveBySticks(new MecanumDriveInput(-0.019669090855358604, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(-0.5829567733418531, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(33);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(447);
        robot.driveBySticks(new MecanumDriveInput(-0.28387778867124064, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.00802708046666258, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(31);
        robot.driveBySticks(new MecanumDriveInput(0.3259479294725697, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(2677);
        robot.driveBySticks(new MecanumDriveInput(0.14515280179848442, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(158);
        robot.driveBySticks(new MecanumDriveInput(0.0, 1.4936458017768864E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4221577907675405, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.7801416042624152, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(165);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(153);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.3965407873994692, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1203);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4909745467016734, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, 2.942330697857297E-6, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(361);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(397);
        robot.driveBySticks(new MecanumDriveInput(0.0, -9.303438608190281E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.31506578323138545, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(51);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.760614587995176, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(291);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.03656187194175954, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(30);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(119);
        robot.driveBySticks(new MecanumDriveInput(-0.02141131730120552, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(-0.6857644242693178, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(76);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 5.301529950883216E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 9.303438608190281E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(337);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(583);
        robot.driveBySticks(new MecanumDriveInput(-0.615993412972134, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(293);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.010038101258904406, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.12673771057083505, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.31506578323138545, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4092156171283124, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(119);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4221577907675405, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(470);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4221577907675405, -3.2211098537850987E-4));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4221577907675405, -0.018024033741088605));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(54);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.43536991164075156, -0.12673771057083505));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(15);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.43536991164075156, -0.46261542243022674));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.43536991164075156, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(82);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.43536991164075156, -0.31506578323138545));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.43536991164075156, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(244);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.2940334634944208, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.06110105771077212, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(404);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.12096469607021738));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.5993233445002052));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(67);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.019669090855358604, 0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(52);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.3600919190510958, 0.031677585292466705));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(33);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.5204695901645724, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.07668417689676373, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(284);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.0685979093060748, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(54);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(100);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.031677585292466705, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(261);
        robot.driveBySticks(new MecanumDriveInput(0.0, -2.6519064606397182E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(101);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(66);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.3600919190510958, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.010038101258904406, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1748);
    }
}