package org.firstinspires.ftc.teamcode.opmodes.autonomous;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.robots.CompetitionRobot;
import org.firstinspires.ftc.teamcode.robots.CompetitionRobotI;
import org.firstinspires.ftc.teamcode.robots.drivetrains.mecanum.MecanumDriveInput;

@Autonomous(name="BlueInside")
public class BlueInside extends LinearOpMode {
    @Override
    public void runOpMode() {
        CompetitionRobotI robot = CompetitionRobot.instantiate(hardwareMap);
        waitForStart();
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(591);
        robot.driveBySticks(new MecanumDriveInput(-1.075748404948325E-5, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(-0.057566704144755655, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(-0.3965407873994692, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(914);
        robot.driveBySticks(new MecanumDriveInput(-0.6502551947114619, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(-2.247940499531374E-4, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(30);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(310);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.00123459723589007, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.21091500583292616, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(2.247940499531374E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0026429595005789787, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.015014269601226768, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.023253501292314464, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(0.02519843817610708, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(135);
        robot.driveBySticks(new MecanumDriveInput(0.027248902280722298, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(243);
        robot.driveBySticks(new MecanumDriveInput(0.027248902280722298, -0.3370778087137927, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.00123459723589007, -0.012359729889232902, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(31);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(83);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.004212055625910014));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.1099499616497697));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.2455930084954745));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(63);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.3484582091687397));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.371981726574546));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(112);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.3841304199527754));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(252);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.3965407873994692));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.4092156171283124));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.4766543887738611));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.5204695901645724));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(65);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.6678524844062314));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.6857644242693178));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(203);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.00713107361325091));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(266);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.3600919190510958));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(119);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.11536970916775731));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(129);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0015217918779346867, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.064777192057204, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.044791322943135335, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(190);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.023253501292314464, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(115);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.46261542243022674, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(68);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.003634606445093873, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(19);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(192);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.011158694447594155, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.3484582091687397, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(132);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.1723678461856297, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(247);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0685979093060748, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(75);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.3600919190510958, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.010038101258904406, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(53);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(505);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.16527056709357968, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.7801416042624152, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(113);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0018503921535399936, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(246);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(985);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.006304360327048331, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.064777192057204, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.14515280179848442, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.3841304199527754, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.6329697669713245, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(26);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1646);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.2455930084954745, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, -1.4936458017768864E-4, -0.00123459723589007));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(24);
        robot.driveBySticks(new MecanumDriveInput(0.0, -1.4936458017768864E-4, -0.08996758448434951));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(12);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.08996758448434951));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.25481909209924314));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.4488548594570853));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(33);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.4909745467016734));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.5055786844273488));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(834);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.5204695901645724));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.5993233445002052));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.6857644242693178));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(519);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.19487283628185792));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(188);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.003634606445093873));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(51);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.044791322943135335));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.07256597038570443));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.08996758448434951));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0947142560201916));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(130);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.12096469607021738));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.1583708331154009));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.2739586939734411));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(23);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.4092156171283124));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(248);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.371981726574546));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(129);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.027248902280722298, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5511229701111388, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(54);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1297);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5511229701111388, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.023253501292314464, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(276);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(603);
        robot.driveBySticks(new MecanumDriveInput(0.0, -9.860191826837608E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.015014269601226768, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.029407688581613814, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.03918182959632902, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.05417134314546949, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.064777192057204, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.12096469607021738, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.20278817796624368, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.2739586939734411, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(74);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.28387778867124064, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(5.301529950883216E-5, -0.3259479294725697, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(9.303438608190281E-5, -0.3600919190510958, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(4.4410399168743177E-4, -0.5204695901645724, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(7.732697716841073E-4, -0.6857644242693178, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(9.860191826837608E-4, -0.7414161629845973, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(0.00123459723589007, -0.7414161629845973, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(31);
        robot.driveBySticks(new MecanumDriveInput(0.0015217918779346867, -0.7414161629845973, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(231);
        robot.driveBySticks(new MecanumDriveInput(0.0015217918779346867, -0.760614587995176, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(83);
        robot.driveBySticks(new MecanumDriveInput(0.0018503921535399936, -0.760614587995176, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(247);
        robot.driveBySticks(new MecanumDriveInput(5.301529950883216E-5, -0.07256597038570443, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, -2.247940499531374E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(305);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.0018503921535399936, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(78);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(62);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.029407688581613814));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(70);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(113);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.1583708331154009));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -9.303438608190281E-5));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(228);
        robot.driveBySticks(new MecanumDriveInput(0.0, -2.853865811446184E-7, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.26427339118733695, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(92);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.3484582091687397, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.011158694447594155, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(198);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.031677585292466705, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4909745467016734, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(66);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.5993233445002052, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(21);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.047786435062742355, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(4080);
    }
}