package org.firstinspires.ftc.teamcode.opmodes.autonomous;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.robots.CompetitionRobot;
import org.firstinspires.ftc.teamcode.robots.CompetitionRobotI;
import org.firstinspires.ftc.teamcode.robots.drivetrains.mecanum.MecanumDriveInput;

@Autonomous(name="RedInside")
public class RedInside extends LinearOpMode {
    @Override
    public void runOpMode() {
        CompetitionRobotI robot = CompetitionRobot.instantiate(hardwareMap);
        waitForStart();
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(62);
        robot.driveBySticks(new MecanumDriveInput(-1.075748404948325E-5, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(-0.057566704144755655, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(-0.5204695901645724, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(874);
        robot.driveBySticks(new MecanumDriveInput(-0.0947142560201916, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(9.303438608190281E-5, 0.011158694447594155, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.011158694447594155, 0.760614587995176, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(61);
        robot.driveBySticks(new MecanumDriveInput(0.012359729889232902, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(19);
        robot.driveBySticks(new MecanumDriveInput(0.004847638130838766, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.002223185106844592, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(9.860191826837608E-4, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(5.935607817367757E-4, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(137);
        robot.driveBySticks(new MecanumDriveInput(9.303438608190281E-5, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(15);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(222);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.15166585603740818, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(21);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(81);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.011158694447594155));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.13269154088329538));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(57);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.26427339118733695));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(80);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.5668909112833928));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(366);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.050912186499228546));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(452);
        robot.driveBySticks(new MecanumDriveInput(0.0, -3.2211118038174137E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.0685979093060748, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(23);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.5668909112833928, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(25);
        robot.driveBySticks(new MecanumDriveInput(2.6519064606397182E-5, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(100);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.006304360327048331, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(84);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.00713107361325091, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4909745467016734, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(307);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(339);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.10470266530256947, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(33);
        robot.driveBySticks(new MecanumDriveInput(-2.853865811446184E-7, 0.4909745467016734, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(24);
        robot.driveBySticks(new MecanumDriveInput(-1.4936458017768864E-4, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(-2.247940499531374E-4, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(73);
        robot.driveBySticks(new MecanumDriveInput(-2.853865811446184E-7, 0.12096469607021738, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(14);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(842);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(576);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.3841304199527754, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(6);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(88);
        robot.driveBySticks(new MecanumDriveInput(4.4410399168743177E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(67);
        robot.driveBySticks(new MecanumDriveInput(0.003634606445093873, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(164);
        robot.driveBySticks(new MecanumDriveInput(0.004212055625910014, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(972);
        robot.driveBySticks(new MecanumDriveInput(9.303438608190281E-5, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(-2.942330697857297E-6, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(-0.26427339118733695, -0.371981726574546, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(-0.6678524844062314, -0.044791322943135335, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1158);
        robot.driveBySticks(new MecanumDriveInput(-0.8, -0.0026429595005789787, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(160);
        robot.driveBySticks(new MecanumDriveInput(-0.8, -2.6519064606397182E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1472);
        robot.driveBySticks(new MecanumDriveInput(-0.6329697669713245, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(51);
        robot.driveBySticks(new MecanumDriveInput(-0.047786435062742355, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(24);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(127);
        robot.driveBySticks(new MecanumDriveInput(0.0, 5.301529950883216E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4488548594570853, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(240);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.2455930084954745, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(195);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.03656187194175954, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4909745467016734, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(19);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(722);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5204695901645724, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.004212055625910014, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(83);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(477);
        robot.driveBySticks(new MecanumDriveInput(0.0, -2.247940499531374E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.371981726574546, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.7801416042624152, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(75);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(340);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4221577907675405, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(26);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.01647335237122514, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.002223185106844592));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.12673771057083505));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(53);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.7039938025144066));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(29);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(474);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.5668909112833928));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.4092156171283124));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.08996758448434951));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 9.860191826837608E-4));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(160);
        robot.driveBySticks(new MecanumDriveInput(0.0, 2.8538562550931054E-7, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.004212055625910014, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.047786435062742355, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(29);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0809553170529378, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(69);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.3259479294725697, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4092156171283124, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(57);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4488548594570853, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.46261542243022674, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(163);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4766543887738611, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(295);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4766543887738611, -0.003634606445093873));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(21);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4766543887738611, -0.0685979093060748));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.4766543887738611, -0.179665458605236));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.179665458605236, -0.30442850665666643));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.005544144454534878, -0.3259479294725697));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.3370778087137927));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(77);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.050912186499228546));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(148);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 1.4936458017768864E-4));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(63);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.236592352162346));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.7414161629845973));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.219256168453269));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(31);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.00123459723589007));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(216);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.16527056709357968, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(32);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.6857644242693178, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.26427339118733695, 0.03656187194175954));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0031125044330914766, 0.31506578323138545));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.7414161629845973));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.007131078225675987));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(78);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.26427339118733695, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.7414161629845973, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.219256168453269, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(84);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.003634606445093873));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.006304360327048331));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(118);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0026429595005789787, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.7039938025144066, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(83);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5055786844273488, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.023253501292314464, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(72);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 2.853865811446184E-7));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.019669090855358604));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(52);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.10470266530256947));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(28);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.20278817796624368));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, 0.02519843817610708));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(2418);
    }
}