package org.firstinspires.ftc.teamcode.opmodes.autonomous;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.robots.CompetitionRobot;
import org.firstinspires.ftc.teamcode.robots.CompetitionRobotI;
import org.firstinspires.ftc.teamcode.robots.drivetrains.mecanum.MecanumDriveInput;

@Autonomous(name="RedOutside")
public class RedOutside extends LinearOpMode {
    @Override
    public void runOpMode() {
        CompetitionRobotI robot = CompetitionRobot.instantiate(hardwareMap);
        waitForStart();
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(672);
        robot.driveBySticks(new MecanumDriveInput(-0.00802708046666258, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(-0.6857644242693178, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(756);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.012359729889232902, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.044791322943135335, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(-0.5993233445002052, 0.12096469607021738, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(-0.05417134314546949, 0.615993412972134, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(43);
        robot.driveBySticks(new MecanumDriveInput(-2.6519064606397182E-5, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(1.075748404948325E-5, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(59);
        robot.driveBySticks(new MecanumDriveInput(5.935607817367757E-4, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(26);
        robot.driveBySticks(new MecanumDriveInput(9.860191826837608E-4, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(234);
        robot.driveBySticks(new MecanumDriveInput(5.301529950883216E-5, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(217);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.044791322943135335, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(57);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(498);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -9.860191826837608E-4));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(21);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.050912186499228546));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.3484582091687397));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.6329697669713245));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(78);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.722543541016994));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.7414161629845973));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.760614587995176));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.7801416042624152));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(78);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.3841304199527754));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(30);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.015014269601226768));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(64);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(785);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -2.6519064606397182E-5));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.050912186499228546));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.2455930084954745));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.06110105771077212));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -9.303438608190281E-5));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(91);
        robot.driveBySticks(new MecanumDriveInput(0.0, -1.4936458017768864E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.4488548594570853, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(23);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.057566704144755655, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(62);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.004847638130838766));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.5511229701111388));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(39);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.8));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(47);
        robot.driveBySticks(new MecanumDriveInput(0.0, 2.247940499531374E-4, -0.03918182959632902));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(30);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.22781433488617253, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.7414161629845973, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(134);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0685979093060748, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(29);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(159);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0809553170529378, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.6329697669713245, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(121);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.044791322943135335, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(46);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(298);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.03918182959632902, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(54);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(168);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.064777192057204, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(29);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(406);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.00713107361325091, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.3259479294725697, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(35);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.00713107361325091, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(242);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(791);
        robot.driveBySticks(new MecanumDriveInput(0.0, -1.075748404948325E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(84);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.2455930084954745, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.760614587995176, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(37);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1592);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.19487283628185792, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(-1.075748404948325E-5, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(-0.08996758448434951, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(-0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(3016);
        robot.driveBySticks(new MecanumDriveInput(-0.4092156171283124, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(99);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(89);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.050912186499228546, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(14);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5993233445002052, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(49);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(293);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5204695901645724, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(20);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(170);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.057566704144755655, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.5204695901645724, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(514);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.11536970916775731, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(-1);
        robot.setRightServoPosition(1);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(162);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(599);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.19487283628185792, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(81);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(211);
        robot.driveBySticks(new MecanumDriveInput(-1.4936458017768864E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(27);
        robot.driveBySticks(new MecanumDriveInput(-5.935607817367757E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(38);
        robot.driveBySticks(new MecanumDriveInput(-7.732697716841073E-4, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(105);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(0.08996758448434951, -0.2455930084954745, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(75);
        robot.driveBySticks(new MecanumDriveInput(0.8, -0.004212055625910014, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.8, -1.075748404948325E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(112);
        robot.driveBySticks(new MecanumDriveInput(0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(852);
        robot.driveBySticks(new MecanumDriveInput(0.16527056709357968, -1.075748404948325E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(2.247940499531374E-4, -1.075748404948325E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(41);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(122);
        robot.driveBySticks(new MecanumDriveInput(0.0, -4.4410399168743177E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(34);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.2940334634944208, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(160);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.00802708046666258, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(88);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(107);
        robot.driveBySticks(new MecanumDriveInput(2.8538562550931054E-7, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(0.06110105771077212, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(53);
        robot.driveBySticks(new MecanumDriveInput(0.8, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(149);
        robot.driveBySticks(new MecanumDriveInput(0.031677585292466705, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(50);
        robot.driveBySticks(new MecanumDriveInput(0.0, -7.732697716841073E-4, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(-0.02141131730120552, -0.15166585603740818, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(30);
        robot.driveBySticks(new MecanumDriveInput(-0.06110105771077212, -0.7801416042624152, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(-0.019669090855358604, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(44);
        robot.driveBySticks(new MecanumDriveInput(-0.011158694447594155, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(40);
        robot.driveBySticks(new MecanumDriveInput(-0.004212055625910014, -0.4909745467016734, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.02519843817610708, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(42);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(257);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.013643991511791055, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(22);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.371981726574546, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(74);
        robot.driveBySticks(new MecanumDriveInput(0.0018503921535399936, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(48);
        robot.driveBySticks(new MecanumDriveInput(2.942330697857297E-6, -0.008995158096142276, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(36);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(373);
        robot.driveBySticks(new MecanumDriveInput(0.0, -5.301529950883216E-5, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(30);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.5204695901645724, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(24);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.8, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(92);
        robot.driveBySticks(new MecanumDriveInput(0.0, -0.13882897522128346, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(45);
        robot.driveBySticks(new MecanumDriveInput(0.0, 0.0, -0.0));
        robot.setLiftPower(0.0);
        robot.setLeftServoPosition(0);
        robot.setRightServoPosition(0);
        robot.setPitchPosition(0.0);
        robot.setIntakePosition(0.6);
        robot.setGripperPosition(0.0);
        sleep(1296);
    }
}